config/routes.rb
Rails.application.routes.draw do
  resources :imports
  resources :users
  root 'imports#index'

  # Sidekiq web view
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/import.rb
class Import < ApplicationRecord
  has_one_attached :import_file
end

app/models/user.rb
class User < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Rails.application.routes.url_helpers

end

app/controllers/imports_controller.rb
class ImportsController < ApplicationController
  before_action :set_import, only: [:show, :edit, :update, :destroy]

  # GET /imports
  # GET /imports.json
  def index
    @imports = Import.all
    @import = Import.new
    @users = User.all
  end

  # GET /imports/1
  # GET /imports/1.json
  def show
  end

  # GET /imports/new
  def new
    @import = Import.new
  end

  # GET /imports/1/edit
  def edit
  end

  # POST /imports
  # POST /imports.json
  def create
    @import = Import.new(import_params)
    csv_path = ActiveStorage::Blob.service.send(:path_for, @import.import_file.key)
    ImportsWorker.perform_async(csv_path)

    respond_to do |format|
      if @import.save
        format.html { redirect_to root_path, notice: 'Import was successfully created.' }
        format.json { render :show, status: :created, location: @import }
      else
        format.html { render :new }
        format.json { render json: @import.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /imports/1
  # PATCH/PUT /imports/1.json
  def update
    respond_to do |format|
      if @import.update(import_params)
        format.html { redirect_to root_path, notice: 'Import was successfully updated.' }
        format.json { render :show, status: :ok, location: @import }
      else
        format.html { render :edit }
        format.json { render json: @import.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /imports/1
  # DELETE /imports/1.json
  def destroy
    @import.destroy
    respond_to do |format|
      format.html { redirect_to imports_url, notice: 'Import was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_import
      @import = Import.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def import_params
      params.require(:import).permit(:import_file)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @users = User.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/imports_helper.rb
module ImportsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/imports/_form.html.erb
<%= form_with(model: import, local: true, class: "p-2") do |form| %>
  <% if import.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(import.errors.count, "error") %> prohibited this import from being saved:</h2>

      <ul>
        <% import.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="p-2">
    <label for="<%= form.object_name %>_import_file" class="file-field">
      <%= form.file_field :import_file, class: "full-width" %>
      <span >Custom upload file</span>
    </label>
  </div>
  <div>
    <%= form.submit "Import file", class: "mt-3 btn p-2 full-width btn-dark" %>
  </div>
<% end %>

app/views/imports/edit.html.erb
<h1>Editing Import</h1>

<%= render 'form', import: @import %>

<%= link_to 'Show', @import %> |
<%= link_to 'Back', imports_path %>

app/views/imports/index.html.erb
<div>
  <h1>CSV importer</h1>
  <p>This is a simple demo of a CSV importer</p>
  <p>Example CSV file to be imported to model can be found in root/csv</p>
</div>
<div class="m-4 card">
  <div class="form p-5">
    <%= render 'form', import: @import %>
  </div>
</div>

<%= render 'imports/partials/list_of_imports' %>

<%= render 'imports/partials/list_of_users' %>

app/views/imports/new.html.erb
<h1>New Import</h1>

<%= render 'form', import: @import %>

<%= link_to 'Back', imports_path %>

app/views/imports/partials/_list_of_imports.html.erb
<div class="table mt-5 ml-2">
  <table>
    <thead>
      <tr class="first">
        <th class="id">ID</th>
        <th>Date</th>
        <th>Time</th>
        <th>Filename</th>
        <th class="last">URL</th>
      </tr>
    </thead>
    <tbody>
      <% if @imports.empty? %>
      <tr>
        <td colspan="3" class="last">There are no files in the database</td>
      </tr>
      <% else %>
        <% @imports.each do |import| %>
          <tr class="p-5">
            <td><%= import.id %></td>
            <td><%= import.created_at.strftime("%C.%b %Y") %></td>
            <td><%= import.created_at.strftime("%H:%M") %></td>
            <td><%= import.import_file.filename %></td>
            <td class="last"><%= url_for(import.import_file) %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/imports/partials/_list_of_users.html.erb
<div class="table mt-5 ml-2 pl-2">
  <table>
    <thead>
      <tr class="first">
        <th class="id">ID</th>
        <th>Firstname</th>
        <th class="last">Lastname</th>
      </tr>
    </thead>
    <tbody>
      <% if @users.empty? %>
      <tr>
        <td colspan="3" class="last">There are no users in the database</td>
      </tr>
      <% else %>
        <tr>
          <td colspan="3" class="last">There are <%= @users.count %> users.</td>
        </tr>
        <% @users.each do |user| %>
          <tr class="p-5">
            <td><%= user.id %></td>
            <td><%= user.first_name %></td>
            <td class="last"><%= user.last_name %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/imports/show.html.erb
<%= link_to 'Edit', edit_import_path(@import) %> |
<%= link_to 'Back', imports_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SidekiqDemo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="sidebar">
      <%= render partial: "layouts/partials/sidebar" %>
    </div>
    <div class="content">

      <% flash.each do |type, msg| %>
        <% if type="notice" %>
          <div class="flash notice">
        <% else %>
          <div class="flash alert">
        <% end %>
          <%= msg %>
        </div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/partials/_sidebar.html.erb
  <a href="#">Something</a>
  <a href="#">Something</a>
  <a href="#">Something</a>
  <a href="#">Something</a>

app/views/static_pages/home.html.erb
<div>
  <h1>CSV importer</h1>
  <p>This is a simple demo of a CSV importer</p>
  <p>Example CSV file to be imported to model can be found in root/csv</p>
</div>
<div class="m-4 card">
  <div class="form p-5">
    <%= form_tag import_path, multipart: true, class: "p-2" do %>
      <div class="p-2">
        <label for="import_file" class="file-field">
          <%= file_field_tag :import_file, class: "full-width" %>
          Custom upload file
        </label>
      </div>
      <%= submit_tag "Import", class: "mt-3 btn p-2 full-width btn-dark" %>
    <% end %>
  </div>
</div>

<div class="table mt-5 ml-2">
  <table>
    <thead>
      <tr class="first">
        <th class="id">ID</th>
        <th>Firstname</th>
        <th class="last">Lastname</th>
      </tr>
    </thead>
    <tbody>
      <% if @users.empty? %>
      <tr>
        <td colspan="3" class="last">There are no users in the database</td>
      </tr>
      <% else %>
        <% @users.each do |user| %>
          <tr class="p-5">
            <td><%= user.id %></td>
            <td><%= user.first_name %></td>
            <td class="last"><%= user.last_name %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>


<div>
  <% User.first.import_files.each do |f| %>
    <%= f.filename %>
  <% end %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>